-- Run this file once in Supabase SQL Editor.
-- It creates the account profiles, patient assessment storage, and row-level access controls.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  consented_at timestamptz,
  created_at timestamptz not null default now(),
  last_active_at timestamptz not null default now()
);

create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  question text not null check (char_length(question) between 1 and 2000),
  patient jsonb not null,
  answer text not null,
  prediction jsonb,
  created_at timestamptz not null default now()
);

create index if not exists assessments_user_created_idx
  on public.assessments (user_id, created_at desc);

create or replace function public.is_scoliosis_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from auth.users
    where id = auth.uid()
      and lower(email) = 'gracehejiamei@gmail.com'
      and email_confirmed_at is not null
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, display_name, role, consented_at)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    coalesce(new.raw_user_meta_data ->> 'display_name', ''),
    case when lower(coalesce(new.email, '')) = 'gracehejiamei@gmail.com' then 'admin' else 'user' end,
    case when coalesce((new.raw_user_meta_data ->> 'consent')::boolean, false) then now() else null end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.assessments enable row level security;

drop policy if exists "profile owner or admin can read" on public.profiles;
create policy "profile owner or admin can read"
  on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_scoliosis_admin());

drop policy if exists "profile owner can update" on public.profiles;
create policy "profile owner can update"
  on public.profiles for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists "assessment owner or admin can read" on public.assessments;
create policy "assessment owner or admin can read"
  on public.assessments for select to authenticated
  using (user_id = auth.uid() or public.is_scoliosis_admin());

drop policy if exists "assessment owner can insert" on public.assessments;
create policy "assessment owner can insert"
  on public.assessments for insert to authenticated
  with check (user_id = auth.uid());

revoke all on public.profiles from anon, authenticated;
revoke all on public.assessments from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, last_active_at) on public.profiles to authenticated;
grant select, insert on public.assessments to authenticated;
grant usage, select on sequence public.assessments_id_seq to authenticated;
grant execute on function public.is_scoliosis_admin() to authenticated;


